pmi3817/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('startups/', include('startups.urls')),
    path('admin/', admin.site.urls),
]

startups/urls.py
from django.urls import path

from . import views

app_name = 'startups'
urlpatterns = [
    #path('', views.list_startups, name='index'),
    path('', views.StartupListView.as_view(), name='index'),

    path('search/', views.search_startups, name='search'),

    #path('create/', views.create_startups, name='create'),
    path('create/', views.StartupCreateView.as_view(), name='create'),

    #path('<int:startup_id>/', views.detail_startup, name='detail'),
    path('<int:pk>/', views.StartupDetailView.as_view(), name='detail'),

    #path('update/<int:startup_id>/', views.update_startup, name='update'),
    path('update/<int:pk>/', views.StartupUpdateView.as_view(), name='update'),

    #path('delete/<int:startup_id>/', views.delete_startup, name='delete'),
    path('delete/<int:pk>/', views.StartupDeleteView.as_view(), name='delete'),

    path('<int:startup_id>/comment/', views.create_comment, name='comment'),

    path('category/', views.CategoryListView.as_view(), name='category'),

    path('category/<int:pk>', views.CategoryDetailView.as_view(), name ='ind_category')
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

startups/models.py
from django.db import models
from django.conf import settings
from django.db.models.fields import DateTimeField
from django.utils import timezone


class Startup(models.Model):
    name = models.CharField(max_length=255)
    dor = models.CharField(max_length=1000)
    logo_url = models.URLField(max_length=500, null=True)

    def __str__(self):
        return f'{self.name} ({self.dor})'


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=400)
    startup = models.ForeignKey(Startup, on_delete=models.CASCADE)
    data = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    startups = models.ManyToManyField(Startup)

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

startups/forms.py
from django.forms import ModelForm
from .models import Startup, Comment


class StartupForm(ModelForm):
    class Meta:
        model = Startup
        fields = [
            'name',
            'dor',
            'logo_url',
        ]
        labels = {
            'name': 'Nome da Startup',
            'dor': 'Dor da Startup',
            'logo_url': 'URL da Logo',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Nome',
            'text': 'Comentário sobre a startup',
        }

startups/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render
from django.http import HttpResponse
from django.urls.base import reverse_lazy
from .temp_data import startup_data
from .models import Startup, Comment, Category
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .forms import StartupForm, CommentForm


#def detail_startup(request, startup_id):
#    startup = get_object_or_404(Startup, pk=startup_id)
#    context = {'startup': startup}
#    return render(request, 'startups/detail.html', context)
#    Deu certo

class StartupDetailView(generic.DetailView):
    model = Startup
    template_name = 'startups/detail.html'

#def list_startups(request):
#    startup_list = Startup.objects.all()
#    context = {'startup_list': startup_list}
#    return render(request, 'startups/index.html', context)
#    Deu certo

class StartupListView(generic.ListView):
    model = Startup
    template_name = 'startups/index.html'

def search_startups(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        startup_list = Startup.objects.filter(name__icontains=search_term)
        context = {"startup_list": startup_list}
    return render(request, 'startups/search.html', context)

#def create_startups(request):
#    if request.method == 'POST':
#        form = StartupForm(request.POST)
#        if form.is_valid():
#            startup_name = form.cleaned_data['name']
#            startup_dor = form.cleaned_data['dor']
#            startup_logo_url = form.cleaned_data['logo_url']
#            startup = Startup(name=startup_name,
#                          dor=startup_dor,
#                          logo_url=startup_logo_url)
#            startup.save()
#            return HttpResponseRedirect(
#                reverse('startups:detail', args=(startup.id, )))
#    else:
#        form = StartupForm()
#        context = {'form': form}
#        return render(request, 'startups/create.html', context)

class StartupCreateView(generic.CreateView):
    model = Startup
    template_name = 'startups/create.html'
    form_class = StartupForm
    success_url = reverse_lazy('startups:index')

'''
def update_startup(request, startup_id):
    startup = get_object_or_404(Startup, pk=startup_id)

    if request.method == "POST":
        form = StartupForm(request.POST)
        if form.is_valid():
            startup.name = form.cleaned_data['name']
            startup.dor = form.cleaned_data['dor']
            startup.logo_url = form.cleaned_data['logo_url']
            startup.save()
            return HttpResponseRedirect(
                reverse('startups:detail', args=(startup.id, )))
    else:
        form = StartupForm(
            initial={
                'name': startup.name,
                'dor': startup.dor,
                'logo_url': startup.logo_url
            })

    context = {'startup': startup, 'form': form}
    return render(request, 'startups/update.html', context)
'''

class StartupUpdateView(generic.UpdateView):
    model = Startup
    fields = ['name', 'dor', 'logo_url']
    template_name = 'startups/update.html'
    forms_class = StartupForm
    success_url = reverse_lazy('startups:index')

'''
def delete_startup(request, startup_id):
    startup = get_object_or_404(Startup, pk=startup_id)

    if request.method == "POST":
        startup.delete()
        return HttpResponseRedirect(reverse('startups:index'))

    context = {'startup': startup}
    return render(request, 'startups/delete.html', context)
'''
class StartupDeleteView(generic.DeleteView):
    model = Startup
    template_name = 'startups/delete.html'
    success_url = reverse_lazy('startups:index')

def create_comment(request, startup_id):
    startup = get_object_or_404(Startup, pk=startup_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            startup=startup)
            comment.save()
            return HttpResponseRedirect(
                reverse('startups:detail', args=(startup_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'startup': startup}
    return render(request, 'startups/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'startups/category.html'

class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'startups/create_list.html'
    fields = ['name', 'author', 'startups']
    success_url = reverse_lazy('startups:lists')

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'startups/ind_category.html'

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

startups/templates/startups/category.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias das Startups por área de atuação</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <h3><a href="{% url 'startups:ind_category' category.id %}">{{category.name}}</h3>
        </header>
        <div class="lista-de-cards">
            {% for startup in category.startups.all %}
            <div class="card">
                <a href="{% url 'startups:detail' startup.id %}"><img src="{{ startup.logo_url }}"
                        alt="Logo da Startup '{{ startup.name}}'"></a>
                <p>{{ startup.name }}</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}
</section>

{% endblock content %}

startups/templates/startups/comment.html
{% extends 'base.html' %}

{% block title %}
Comentar Startup
{% endblock title %}

{% block content %}
<h2>Comentar sobre a atividade da startup {{ startup.name }}</h2>

<form action="{% url 'startups:comment' startup.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'startups:detail' startup.id %}">Voltar para a página de detalhamento da Startup</a></p>
{% endblock content %}

startups/templates/startups/create.html
{% extends 'base.html' %}

{% block title %}
Criação de startup
{% endblock title %}

{% block content %}
<h2>Inserir Nova Startup</h2>
<form method="POST" action="{% url 'startups:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar Startup</button>
</form>

{% endblock content %}

startups/templates/startups/delete.html
{% extends 'base.html' %}

{% block title %}
Excluir startup
{% endblock title %}

{% block content %}
<form action="{% url 'startups:delete' startup.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a startup "{{ startup.name }}"?
    </p>
    <button type="submit">Apagar Startup</button>
</form>

{% endblock content %}

startups/templates/startups/detail.html
{% extends 'base.html' %}

{% block title %}
{{ startup.name }}
{% endblock title %}

{% block content %}
<h2>Detalhes da Startup {{ startup.name }}</h2>

<section class="dados-de-filme">
    <img src="{{ startup.logo_url }}" alt="Logo da startup {{ startup.name}}" width="80%" style="margin-left: auto; margin-right: auto;">
    <ul>
        <li>Nome da Startup: {{ startup.name }}</li>
        <li>Dor: {{ startup.dor }} </li>
        <hr>
        <li>Incluso nas categorias: </li>
        <ul>
            {% for category in startup.category_set.all %}
                <li> <a href="{% url 'startups:ind_category' category.id %}"> {{ category }}</a> </li>
            {% endfor %}
        </ul>
        <hr>
        <li><a href="{% url 'startups:update' startup.id %}">Editar informações da Startup</a></li>
        <li><a href="{% url 'startups:delete' startup.id %}">Apagar Startup</a></li>
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Comentários sobre a Startup {{ startup.name }}</h3>
    </header>
    <ul>
        {% if startup.comment_set.all %}
            {% for comment in startup.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }}, Data de publicação: {{ comment.data }} </figcaption>
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existem comentários sobre as atividades desta startup.</p>
        {% endif %}
    </ul>
    
    <hr>

    <a href="{% url 'startups:comment' startup.pk %}"><button>Comente sobre a atividade desta Startup!</button></a>
</section>

{% endblock content %}

startups/templates/startups/ind_category.html
{% extends 'base.html' %}

{% block title %}
{{ category.name }}
{% endblock title %}

{% block content %}
<h2>As {{ category.name }}'s do curso:</h2>

<section>
    
    <hr>
    <article>
        <div class="lista-de-cards">
            {% for startup in category.startups.all %}
            <div class="card">
                <a href="{% url 'startups:detail' startup.id %}"><img src="{{ startup.logo_url }}"
                        alt="Logo da Startup {{ startup.name}}"></a>
                <p><b>{{ startup.name }}</b></p>
            </div>
            {% endfor %}
        </div>
    </article>

</section>


{% endblock content %}

startups/templates/startups/index.html
{% extends 'base.html' %}

{% block title %}
Startups
{% endblock title %}

{% block content %}
<h2>Todos as Startups</h2>
<section>
    <p>Busca algo específico? <a href="{% url 'startups:search' %}">Buscar por Startups.</a></p>
    <p>Para criar uma nova startup, clique <a href="{% url 'startups:create' %}">aqui.</a></p>
</section>
{% if startup_list %}
<section class="lista-de-cards">
    {% for startup in startup_list %}
    <article class="card">
        <a href="{% url 'startups:detail' startup.id %}"><img src="{{ startup.logo_url }}"
                alt="Logo da Startup '{{ startup.name}}'"></a>
        <p> <strong>{{ startup.name }}</strong>; <br> Dor: "{{ startup.dor }}"</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma startup correspondente.</p>
{% endif %}

{% endblock content %}

startups/templates/startups/search.html
{% extends 'base.html' %}

{% block title %}
Buscar startup
{% endblock title %}

{% block content %}
<h2>Busca de Startups por Nome</h2>
<form action="{% url 'startups:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if startup_list %}
<section class="lista-de-cards">
    {% for startup in startup_list %}
    <article class="card">
        <img src="{{ startup.logo_url }}" alt="Logo da Startup {{ startup.name}}">
        <p>{{ startup.name }} <br> Dor:{{ startup.dor }}</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma startup para a busca.</p>
{% endif %}

{% endblock content %}

startups/templates/startups/update.html
{% extends 'base.html' %}

{% block title %}
Atualizar informações de startup
{% endblock title %}

{% block content %}
<h2>Atualizar Dados da Startup "{{ startup.name }}"</h2>
<form method="POST" action="{% url 'startups:update' startup.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar informações</button>
</form>

{% endblock content %}

staticpages/templates/base.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="João Fernando Fernandes Montes">
    <title>
        {% block title %}{% endblock %} | PMI3817 - Empreendedorismo e Inovação em Engenharia
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> 
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logopmi3817.svg' %}" width="120vw"> </a> 
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'startups:index' %}">Todas as startups na disciplina</a></li> 
                <li><a href="{% url 'about' %}">Sobre</a></li>
                <li><a href="{% url 'startups:category' %}">Categorias de Startups</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small><em> Site desenvolvido para a disciplina PMR3304. </em></small>
        </p>
        <p>
            <small>Copyright 2021</small>
        </p>
        <p>
            <small><em><a href="malito:jf-montes@usp.br"></a>jf-montes@usp.br</em></small>
        </p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
<hr>
<p>Site desenvolvido com fins acadêmicos para apoio de alunos e docentes na disciplina PMI 3817.</p>
<p>Aqui você poderá encontrar:</p>
<ul>
    <li>Listagem das startups da disciplina;</li>
    <li>Identificação das apoiadoras da disciplina;</li>
    <li>Corpo de docentes e monitores;</li>
    <li>Agendamento para oficinas (em breve);</li>
</ul>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>PMI3817 - Empreendedorismo e Inovação em Engenharia</i></h1>
<hr>
<p>Clique <a href="https://uspdigital.usp.br/jupiterweb/jupDisciplinaLista?codcg=3&pfxdisval=PMI&tipo=T">aqui</a> para acessar a ementa da disciplina;</p>
<hr>
<p>Corpo docente:</p>
<ul>
    <li>Rubens Approbato Machado Jr.
        <ul>
            <li><a href="https://www.linkedin.com/in/rubensapprobatojr/">LinkedIn</a></li>
            <li>E-mail (<a href="malito:machadra@gmail.com">machadra@gmail.com</a>)</li>
        </ul>
    </li>
    <li>Giorgio De Tomi
        <ul>
            <li><a href="https://www.linkedin.com/in/giorgio-de-tomi/">LinkedIn</a></li>
            <li>E-mail (<a href="malito:gdetomi@usp.br">gdetomi@usp.br</a>)</li>
        </ul>
    </li>
    <li>Antonio Muscat
        <ul>
            <li><a href="https://www.linkedin.com/in/antonio-rafael-namur-muscat-a779a818b/">LinkedIn</a></li>
            <li>E-mail (<a href="malito:armuscat@usp.br">armuscat@usp.br</a>)</li>
        </ul>
    </li>
    <li>Carlos Alberto Fenerich
        <ul>
            <li><a href="https://www.linkedin.com/in/carlosfenerich/">LinkedIn</a></li>
            <li>E-mail (<a href="malito:fenerich.carlos@gmail.com">fenerich.carlos@gmail.com</a>)</li>
        </ul>
    </li>
    <li>José Renato Mannis
        <ul>
            <li><a href="https://www.linkedin.com/in/jrmannis/">LinkedIn</a></li>
            <li>E-mail (<a href="malito:jrmannis@usp.br">jrmannis@usp.br</a>)</li>
        </ul>
    </li>
</ul>
<hr>
<p>Apoiadoras:</p>
<ul>
    <li><a href="https://www.linkedin.com/company/polistart/">PoliStart</a></li>
    <li><a href="https://poliangels.com.br/">PoliAngels</a></li>
    <li><a href="http://www.fdte.org.br/">Fundação para o Desenvolvimento Tecnológico da Engenharia (FDTE)</a></li>
    <li><a href="https://www.accenture.com/br-pt">Accenture Brasil</a></li>
    <li><a href="https://www.ambev.com.br/">Ambev</a></li>
    <li><a href="https://cubo.network/">Cubo</a></li>
    <li><a href="https://www.ibm.com/br-pt">IBM Brasil</a></li>
    <li><a href="https://www.itau.com.br/">Itaú</a></li>
</ul>
<hr>
<p>Monitores:</p>
<ul>
    <li>João Fernando Fernandes Montes
        <ul>
            <li><a href="https://www.linkedin.com/in/joaofernandomontes/">LinkedIn</a></li>
            <li>E-mail (<a href="malito:jf-montes@usp.br">jf-montes@usp.br</a>)</li>
        </ul>
    </li>
    <li>Gabriel Messias Silva
        <ul>
            <li><a href="https://www.linkedin.com/in/gabrielmessiassilva/">LinkedIn</a></li>
            <li>Email (<a href="malito:gabrielmessias@usp.br">gabrielmessias@usp.br</a>)</li>
        </ul>
    </li>
    <li>Ricardo Nicida Kazama
        <ul>
            <li><a href="https://www.linkedin.com/">LinkedIn</a></li>
            <li>Email (<a href="malito:ricakazama@usp.br">ricakazama@usp.br</a>)</li>
        </ul>
    </li>

</ul>

{% endblock content %}